''' === Problem Statement ===

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

pentagonal = lambda n: n * (3*n-1) / 2
hexagonal = lambda n: n * (2 * n - 1)

hexagonal_index = 146
pentagonal_index = 166

hVal = hexagonal(hexagonal_index)
pVal = pentagonal(pentagonal_index)

while True:
    if hVal > pVal:
        pentagonal_index += 1
    elif hVal < pVal:
        hexagonal_index += 1
    else:
        break

    hVal = hexagonal(hexagonal_index)
    pVal = pentagonal(pentagonal_index)

print(hVal)